import Head from 'next/head'
import { Navbar } from '../index'

export const MainLayout = ({children}) => {
  return (
    <div>
      <Head>
        <title>Tototire | page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      {children}
      <p>Hola Mundo</p>
    </div>
  )
}
